[package]
name = "tsr_module"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = ["crates-io"]
description = "TypeScript module resolution for tsr"
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"
include = ["/src/**", "/Cargo.toml", "/README.md", "/LICENSE", "/NOTICE", "/licenses/**"]

[dependencies]
tsr_semver = { version = "0.1.0", path = "../tsr_semver" }
tsr_ast = { version = "0.1.0", path = "../tsr_ast" }
tsr_core = { version = "0.1.0", path = "../tsr_core" }
tsr_tspath = { version = "0.1.0", path = "../tsr_tspath" }
tsr_vfs = { version = "0.1.0", path = "../tsr_vfs" }
tsr_tsoptions = { version = "0.1.0", path = "../tsr_tsoptions" }
tsr_diagnostics = { version = "0.1.0", path = "../tsr_diagnostics" }
tsr_jsstring = { version = "0.1.0", path = "../tsr_jsstring" }
serde = "1"
serde_json = { version = "1", features = ["preserve_order", "raw_value"] }

[lints]
workspace = true
