[package]
name = "tsr_bundled"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = ["crates-io"]
description = "Pinned TypeScript standard library files and bundled filesystem for ts-rust"
repository.workspace = true
readme = "README.md"
include = ["/src/**", "/Cargo.toml", "/README.md", "/LICENSE", "/NOTICE", "/licenses/**", "/bundled/**"]

[dependencies]
tsr_vfs = { version = "0.1.0", path = "../tsr_vfs" }
tsr_jsstring = { version = "0.1.0", path = "../tsr_jsstring" }

[lints]
workspace = true
