[package]
name = "tsr_arena"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
hashbrown = { version = "=0.17.1", default-features = false }
tsr_jsstring = { path = "../tsr_jsstring", version = "0.1.0" }

[dev-dependencies]
serde_json = "1"

[lints]
workspace = true

[features]
harness = []

[[example]]
name = "e3"
required-features = ["harness"]
