[package]
name = "tsr_tspath"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = ["crates-io"]
description = "TypeScript-compatible path operations for ts-rust"
repository.workspace = true
readme = "README.md"
include = ["/src/**", "/Cargo.toml", "/README.md", "/LICENSE", "/NOTICE", "/licenses/**"]

[dependencies]
tsr_core = { version = "0.1.0", path = "../tsr_core" }
tsr_jsstring = { version = "0.1.0", path = "../tsr_jsstring" }

[lints]
workspace = true

[dev-dependencies]
serde_json = "1"
