// Run with the pinned Go runtime; generates the categories used by wordIndices.
package main

import (
	"fmt"
	"runtime"
	"strconv"
	"unicode"
)

func rustInteger(n int) string {
	s := strconv.Itoa(n)
	for i := len(s) - 3; i > 0; i -= 3 {
		s = s[:i] + "_" + s[i:]
	}
	return s
}

func main() {
	if runtime.Version() != "go1.27.1" {
		panic("requires pinned go1.27.1")
	}
	fmt.Println("// Generated by tools/unicode.go with go1.27.1 (Unicode " + unicode.Version + ").")
	fmt.Println("// Go IsUpper/IsLower use Lu/Ll, not the broader derived casing properties.")
	for _, spec := range []struct {
		name string
		test func(rune) bool
	}{{"upper", unicode.IsUpper}, {"lower", unicode.IsLower}} {
		fmt.Printf("pub fn is_%s(rune: i32) -> bool {\n    const RANGES: &[(i32, i32)] = &[\n", spec.name)
		start := -1
		for r := 0; r <= unicode.MaxRune+1; r++ {
			if spec.test(rune(r)) {
				if start < 0 {
					start = r
				}
			} else if start >= 0 {
				fmt.Printf("        (%s, %s),\n", rustInteger(start), rustInteger(r-1))
				start = -1
			}
		}
		fmt.Println("    ];\n    let index = RANGES.partition_point(|&(start, _)| start <= rune);\n    index > 0 && rune <= RANGES[index-1].1\n}")
	}
}
