// Generated from the pinned Go scanner/stringutil tables. Do not edit.
// Upstream 1f70213d4922b434345f639b441681e470c7cfc1; identifier Unicode 15.1; SimpleFold Go Unicode 17.0.0.
pub(crate) const KEYWORDS: &[(&str, u16)] = &[
    ("abstract", 127),
    ("accessor", 128),
    ("any", 132),
    ("as", 129),
    ("assert", 131),
    ("asserts", 130),
    ("async", 133),
    ("await", 134),
    ("bigint", 163),
    ("boolean", 135),
    ("break", 82),
    ("case", 83),
    ("catch", 84),
    ("class", 85),
    ("const", 86),
    ("constructor", 136),
    ("continue", 87),
    ("debugger", 88),
    ("declare", 137),
    ("default", 89),
    ("defer", 166),
    ("delete", 90),
    ("do", 91),
    ("else", 92),
    ("enum", 93),
    ("export", 94),
    ("extends", 95),
    ("false", 96),
    ("finally", 97),
    ("for", 98),
    ("from", 161),
    ("function", 99),
    ("get", 138),
    ("global", 162),
    ("if", 100),
    ("immediate", 139),
    ("implements", 118),
    ("import", 101),
    ("in", 102),
    ("infer", 140),
    ("instanceof", 103),
    ("interface", 119),
    ("intrinsic", 141),
    ("is", 142),
    ("keyof", 143),
    ("let", 120),
    ("module", 144),
    ("namespace", 145),
    ("never", 146),
    ("new", 104),
    ("null", 105),
    ("number", 150),
    ("object", 151),
    ("of", 165),
    ("out", 147),
    ("override", 164),
    ("package", 121),
    ("private", 122),
    ("protected", 123),
    ("public", 124),
    ("readonly", 148),
    ("require", 149),
    ("return", 106),
    ("satisfies", 152),
    ("set", 153),
    ("static", 125),
    ("string", 154),
    ("super", 107),
    ("switch", 108),
    ("symbol", 155),
    ("this", 109),
    ("throw", 110),
    ("true", 111),
    ("try", 112),
    ("type", 156),
    ("typeof", 113),
    ("undefined", 157),
    ("unique", 158),
    ("unknown", 159),
    ("using", 160),
    ("var", 114),
    ("void", 115),
    ("while", 116),
    ("with", 117),
    ("yield", 126),
];
pub(crate) fn keyword_kind(bytes: &[u8]) -> Option<u16> {
    match bytes {
        b"abstract" => Some(127),
        b"accessor" => Some(128),
        b"any" => Some(132),
        b"as" => Some(129),
        b"assert" => Some(131),
        b"asserts" => Some(130),
        b"async" => Some(133),
        b"await" => Some(134),
        b"bigint" => Some(163),
        b"boolean" => Some(135),
        b"break" => Some(82),
        b"case" => Some(83),
        b"catch" => Some(84),
        b"class" => Some(85),
        b"const" => Some(86),
        b"constructor" => Some(136),
        b"continue" => Some(87),
        b"debugger" => Some(88),
        b"declare" => Some(137),
        b"default" => Some(89),
        b"defer" => Some(166),
        b"delete" => Some(90),
        b"do" => Some(91),
        b"else" => Some(92),
        b"enum" => Some(93),
        b"export" => Some(94),
        b"extends" => Some(95),
        b"false" => Some(96),
        b"finally" => Some(97),
        b"for" => Some(98),
        b"from" => Some(161),
        b"function" => Some(99),
        b"get" => Some(138),
        b"global" => Some(162),
        b"if" => Some(100),
        b"immediate" => Some(139),
        b"implements" => Some(118),
        b"import" => Some(101),
        b"in" => Some(102),
        b"infer" => Some(140),
        b"instanceof" => Some(103),
        b"interface" => Some(119),
        b"intrinsic" => Some(141),
        b"is" => Some(142),
        b"keyof" => Some(143),
        b"let" => Some(120),
        b"module" => Some(144),
        b"namespace" => Some(145),
        b"never" => Some(146),
        b"new" => Some(104),
        b"null" => Some(105),
        b"number" => Some(150),
        b"object" => Some(151),
        b"of" => Some(165),
        b"out" => Some(147),
        b"override" => Some(164),
        b"package" => Some(121),
        b"private" => Some(122),
        b"protected" => Some(123),
        b"public" => Some(124),
        b"readonly" => Some(148),
        b"require" => Some(149),
        b"return" => Some(106),
        b"satisfies" => Some(152),
        b"set" => Some(153),
        b"static" => Some(125),
        b"string" => Some(154),
        b"super" => Some(107),
        b"switch" => Some(108),
        b"symbol" => Some(155),
        b"this" => Some(109),
        b"throw" => Some(110),
        b"true" => Some(111),
        b"try" => Some(112),
        b"type" => Some(156),
        b"typeof" => Some(113),
        b"undefined" => Some(157),
        b"unique" => Some(158),
        b"unknown" => Some(159),
        b"using" => Some(160),
        b"var" => Some(114),
        b"void" => Some(115),
        b"while" => Some(116),
        b"with" => Some(117),
        b"yield" => Some(126),
        _ => None,
    }
}
pub(crate) const TOKENS: &[(&str, u16)] = &[
    ("!", 53),
    ("!=", 35),
    ("!==", 37),
    ("#", 62),
    ("%", 44),
    ("%=", 69),
    ("&", 50),
    ("&&", 55),
    ("&&=", 76),
    ("&=", 73),
    ("(", 20),
    (")", 21),
    ("*", 41),
    ("**", 42),
    ("**=", 67),
    ("*=", 66),
    ("+", 39),
    ("++", 45),
    ("+=", 64),
    (",", 27),
    ("-", 40),
    ("--", 46),
    ("-=", 65),
    (".", 24),
    ("...", 25),
    ("/", 43),
    ("/=", 68),
    (":", 58),
    (";", 26),
    ("<", 29),
    ("</", 30),
    ("<<", 47),
    ("<<=", 70),
    ("<=", 32),
    ("=", 63),
    ("==", 34),
    ("===", 36),
    ("=>", 38),
    (">", 31),
    (">=", 33),
    (">>", 48),
    (">>=", 71),
    (">>>", 49),
    (">>>=", 72),
    ("?", 57),
    ("?.", 28),
    ("??", 60),
    ("??=", 77),
    ("@", 59),
    ("[", 22),
    ("]", 23),
    ("^", 52),
    ("^=", 78),
    ("`", 61),
    ("abstract", 127),
    ("accessor", 128),
    ("any", 132),
    ("as", 129),
    ("assert", 131),
    ("asserts", 130),
    ("async", 133),
    ("await", 134),
    ("bigint", 163),
    ("boolean", 135),
    ("break", 82),
    ("case", 83),
    ("catch", 84),
    ("class", 85),
    ("const", 86),
    ("constructor", 136),
    ("continue", 87),
    ("debugger", 88),
    ("declare", 137),
    ("default", 89),
    ("defer", 166),
    ("delete", 90),
    ("do", 91),
    ("else", 92),
    ("enum", 93),
    ("export", 94),
    ("extends", 95),
    ("false", 96),
    ("finally", 97),
    ("for", 98),
    ("from", 161),
    ("function", 99),
    ("get", 138),
    ("global", 162),
    ("if", 100),
    ("immediate", 139),
    ("implements", 118),
    ("import", 101),
    ("in", 102),
    ("infer", 140),
    ("instanceof", 103),
    ("interface", 119),
    ("intrinsic", 141),
    ("is", 142),
    ("keyof", 143),
    ("let", 120),
    ("module", 144),
    ("namespace", 145),
    ("never", 146),
    ("new", 104),
    ("null", 105),
    ("number", 150),
    ("object", 151),
    ("of", 165),
    ("out", 147),
    ("override", 164),
    ("package", 121),
    ("private", 122),
    ("protected", 123),
    ("public", 124),
    ("readonly", 148),
    ("require", 149),
    ("return", 106),
    ("satisfies", 152),
    ("set", 153),
    ("static", 125),
    ("string", 154),
    ("super", 107),
    ("switch", 108),
    ("symbol", 155),
    ("this", 109),
    ("throw", 110),
    ("true", 111),
    ("try", 112),
    ("type", 156),
    ("typeof", 113),
    ("undefined", 157),
    ("unique", 158),
    ("unknown", 159),
    ("using", 160),
    ("var", 114),
    ("void", 115),
    ("while", 116),
    ("with", 117),
    ("yield", 126),
    ("{", 18),
    ("|", 51),
    ("|=", 74),
    ("||", 56),
    ("||=", 75),
    ("}", 19),
    ("~", 54),
];
pub(crate) const NON_BINARY_PROPERTIES: &[(&str, &str)] = &[
    ("General_Category", "General_Category"),
    ("Script", "Script"),
    ("Script_Extensions", "Script_Extensions"),
    ("gc", "General_Category"),
    ("sc", "Script"),
    ("scx", "Script_Extensions"),
];
pub(crate) const BINARY_PROPERTIES: &[&str] = &[
    "AHex",
    "ASCII",
    "ASCII_Hex_Digit",
    "Alpha",
    "Alphabetic",
    "Any",
    "Assigned",
    "Bidi_C",
    "Bidi_Control",
    "Bidi_M",
    "Bidi_Mirrored",
    "CI",
    "CWCF",
    "CWCM",
    "CWKCF",
    "CWL",
    "CWT",
    "CWU",
    "Case_Ignorable",
    "Cased",
    "Changes_When_Casefolded",
    "Changes_When_Casemapped",
    "Changes_When_Lowercased",
    "Changes_When_NFKC_Casefolded",
    "Changes_When_Titlecased",
    "Changes_When_Uppercased",
    "DI",
    "Dash",
    "Default_Ignorable_Code_Point",
    "Dep",
    "Deprecated",
    "Dia",
    "Diacritic",
    "EBase",
    "EComp",
    "EMod",
    "EPres",
    "Emoji",
    "Emoji_Component",
    "Emoji_Modifier",
    "Emoji_Modifier_Base",
    "Emoji_Presentation",
    "Ext",
    "ExtPict",
    "Extended_Pictographic",
    "Extender",
    "Gr_Base",
    "Gr_Ext",
    "Grapheme_Base",
    "Grapheme_Extend",
    "Hex",
    "Hex_Digit",
    "IDC",
    "IDS",
    "IDSB",
    "IDST",
    "IDS_Binary_Operator",
    "IDS_Trinary_Operator",
    "ID_Continue",
    "ID_Start",
    "Ideo",
    "Ideographic",
    "Join_C",
    "Join_Control",
    "LOE",
    "Logical_Order_Exception",
    "Lower",
    "Lowercase",
    "Math",
    "NChar",
    "Noncharacter_Code_Point",
    "Pat_Syn",
    "Pat_WS",
    "Pattern_Syntax",
    "Pattern_White_Space",
    "QMark",
    "Quotation_Mark",
    "RI",
    "Radical",
    "Regional_Indicator",
    "SD",
    "STerm",
    "Sentence_Terminal",
    "Soft_Dotted",
    "Term",
    "Terminal_Punctuation",
    "UIdeo",
    "Unified_Ideograph",
    "Upper",
    "Uppercase",
    "VS",
    "Variation_Selector",
    "White_Space",
    "XIDC",
    "XIDS",
    "XID_Continue",
    "XID_Start",
    "space",
];
pub(crate) const STRING_PROPERTIES: &[&str] = &[
    "Basic_Emoji",
    "Emoji_Keycap_Sequence",
    "RGI_Emoji",
    "RGI_Emoji_Flag_Sequence",
    "RGI_Emoji_Modifier_Sequence",
    "RGI_Emoji_Tag_Sequence",
    "RGI_Emoji_ZWJ_Sequence",
];
pub(crate) const GENERAL_CATEGORIES: &[&str] = &[
    "C",
    "Cased_Letter",
    "Cc",
    "Cf",
    "Close_Punctuation",
    "Cn",
    "Co",
    "Combining_Mark",
    "Connector_Punctuation",
    "Control",
    "Cs",
    "Currency_Symbol",
    "Dash_Punctuation",
    "Decimal_Number",
    "Enclosing_Mark",
    "Final_Punctuation",
    "Format",
    "Initial_Punctuation",
    "L",
    "LC",
    "Letter",
    "Letter_Number",
    "Line_Separator",
    "Ll",
    "Lm",
    "Lo",
    "Lowercase_Letter",
    "Lt",
    "Lu",
    "M",
    "Mark",
    "Math_Symbol",
    "Mc",
    "Me",
    "Mn",
    "Modifier_Letter",
    "Modifier_Symbol",
    "N",
    "Nd",
    "Nl",
    "No",
    "Nonspacing_Mark",
    "Number",
    "Open_Punctuation",
    "Other",
    "Other_Letter",
    "Other_Number",
    "Other_Punctuation",
    "Other_Symbol",
    "P",
    "Paragraph_Separator",
    "Pc",
    "Pd",
    "Pe",
    "Pf",
    "Pi",
    "Po",
    "Private_Use",
    "Ps",
    "Punctuation",
    "S",
    "Sc",
    "Separator",
    "Sk",
    "Sm",
    "So",
    "Space_Separator",
    "Spacing_Mark",
    "Surrogate",
    "Symbol",
    "Titlecase_Letter",
    "Unassigned",
    "Uppercase_Letter",
    "Z",
    "Zl",
    "Zp",
    "Zs",
    "cntrl",
    "digit",
    "punct",
];
pub(crate) const SCRIPT_VALUES: &[&str] = &[
    "Adlam",
    "Adlm",
    "Aghb",
    "Ahom",
    "Anatolian_Hieroglyphs",
    "Arab",
    "Arabic",
    "Armenian",
    "Armi",
    "Armn",
    "Avestan",
    "Avst",
    "Bali",
    "Balinese",
    "Bamu",
    "Bamum",
    "Bass",
    "Bassa_Vah",
    "Batak",
    "Batk",
    "Beng",
    "Bengali",
    "Bhaiksuki",
    "Bhks",
    "Bopo",
    "Bopomofo",
    "Brah",
    "Brahmi",
    "Brai",
    "Braille",
    "Bugi",
    "Buginese",
    "Buhd",
    "Buhid",
    "Cakm",
    "Canadian_Aboriginal",
    "Cans",
    "Cari",
    "Carian",
    "Caucasian_Albanian",
    "Chakma",
    "Cham",
    "Cher",
    "Cherokee",
    "Chorasmian",
    "Chrs",
    "Common",
    "Copt",
    "Coptic",
    "Cpmn",
    "Cprt",
    "Cuneiform",
    "Cypriot",
    "Cypro_Minoan",
    "Cyrillic",
    "Cyrl",
    "Deseret",
    "Deva",
    "Devanagari",
    "Diak",
    "Dives_Akuru",
    "Dogr",
    "Dogra",
    "Dsrt",
    "Dupl",
    "Duployan",
    "Egyp",
    "Egyptian_Hieroglyphs",
    "Elba",
    "Elbasan",
    "Elym",
    "Elymaic",
    "Ethi",
    "Ethiopic",
    "Geor",
    "Georgian",
    "Glag",
    "Glagolitic",
    "Gong",
    "Gonm",
    "Goth",
    "Gothic",
    "Gran",
    "Grantha",
    "Greek",
    "Grek",
    "Gujarati",
    "Gujr",
    "Gunjala_Gondi",
    "Gurmukhi",
    "Guru",
    "Han",
    "Hang",
    "Hangul",
    "Hani",
    "Hanifi_Rohingya",
    "Hano",
    "Hanunoo",
    "Hatr",
    "Hatran",
    "Hebr",
    "Hebrew",
    "Hira",
    "Hiragana",
    "Hluw",
    "Hmng",
    "Hmnp",
    "Hrkt",
    "Hung",
    "Imperial_Aramaic",
    "Inherited",
    "Inscriptional_Pahlavi",
    "Inscriptional_Parthian",
    "Ital",
    "Java",
    "Javanese",
    "Kaithi",
    "Kali",
    "Kana",
    "Kannada",
    "Katakana",
    "Katakana_Or_Hiragana",
    "Kawi",
    "Kayah_Li",
    "Khar",
    "Kharoshthi",
    "Khitan_Small_Script",
    "Khmer",
    "Khmr",
    "Khoj",
    "Khojki",
    "Khudawadi",
    "Kits",
    "Knda",
    "Kthi",
    "Lana",
    "Lao",
    "Laoo",
    "Latin",
    "Latn",
    "Lepc",
    "Lepcha",
    "Limb",
    "Limbu",
    "Lina",
    "Linb",
    "Linear_A",
    "Linear_B",
    "Lisu",
    "Lyci",
    "Lycian",
    "Lydi",
    "Lydian",
    "Mahajani",
    "Mahj",
    "Maka",
    "Makasar",
    "Malayalam",
    "Mand",
    "Mandaic",
    "Mani",
    "Manichaean",
    "Marc",
    "Marchen",
    "Masaram_Gondi",
    "Medefaidrin",
    "Medf",
    "Meetei_Mayek",
    "Mend",
    "Mende_Kikakui",
    "Merc",
    "Mero",
    "Meroitic_Cursive",
    "Meroitic_Hieroglyphs",
    "Miao",
    "Mlym",
    "Modi",
    "Mong",
    "Mongolian",
    "Mro",
    "Mroo",
    "Mtei",
    "Mult",
    "Multani",
    "Myanmar",
    "Mymr",
    "Nabataean",
    "Nag_Mundari",
    "Nagm",
    "Nand",
    "Nandinagari",
    "Narb",
    "Nbat",
    "New_Tai_Lue",
    "Newa",
    "Nko",
    "Nkoo",
    "Nshu",
    "Nushu",
    "Nyiakeng_Puachue_Hmong",
    "Ogam",
    "Ogham",
    "Ol_Chiki",
    "Olck",
    "Old_Hungarian",
    "Old_Italic",
    "Old_North_Arabian",
    "Old_Permic",
    "Old_Persian",
    "Old_Sogdian",
    "Old_South_Arabian",
    "Old_Turkic",
    "Old_Uyghur",
    "Oriya",
    "Orkh",
    "Orya",
    "Osage",
    "Osge",
    "Osma",
    "Osmanya",
    "Ougr",
    "Pahawh_Hmong",
    "Palm",
    "Palmyrene",
    "Pau_Cin_Hau",
    "Pauc",
    "Perm",
    "Phag",
    "Phags_Pa",
    "Phli",
    "Phlp",
    "Phnx",
    "Phoenician",
    "Plrd",
    "Prti",
    "Psalter_Pahlavi",
    "Qaac",
    "Qaai",
    "Rejang",
    "Rjng",
    "Rohg",
    "Runic",
    "Runr",
    "Samaritan",
    "Samr",
    "Sarb",
    "Saur",
    "Saurashtra",
    "Sgnw",
    "Sharada",
    "Shavian",
    "Shaw",
    "Shrd",
    "Sidd",
    "Siddham",
    "SignWriting",
    "Sind",
    "Sinh",
    "Sinhala",
    "Sogd",
    "Sogdian",
    "Sogo",
    "Sora",
    "Sora_Sompeng",
    "Soyo",
    "Soyombo",
    "Sund",
    "Sundanese",
    "Sylo",
    "Syloti_Nagri",
    "Syrc",
    "Syriac",
    "Tagalog",
    "Tagb",
    "Tagbanwa",
    "Tai_Le",
    "Tai_Tham",
    "Tai_Viet",
    "Takr",
    "Takri",
    "Tale",
    "Talu",
    "Tamil",
    "Taml",
    "Tang",
    "Tangsa",
    "Tangut",
    "Tavt",
    "Telu",
    "Telugu",
    "Tfng",
    "Tglg",
    "Thaa",
    "Thaana",
    "Thai",
    "Tibetan",
    "Tibt",
    "Tifinagh",
    "Tirh",
    "Tirhuta",
    "Tnsa",
    "Toto",
    "Ugar",
    "Ugaritic",
    "Unknown",
    "Vai",
    "Vaii",
    "Vith",
    "Vithkuqi",
    "Wancho",
    "Wara",
    "Warang_Citi",
    "Wcho",
    "Xpeo",
    "Xsux",
    "Yezi",
    "Yezidi",
    "Yi",
    "Yiii",
    "Zanabazar_Square",
    "Zanb",
    "Zinh",
    "Zyyy",
    "Zzzz",
];
