[package]
name = "tsr_vfs"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = ["crates-io"]
description = "Virtual filesystem and host contracts for tsr"
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"
include = ["/src/**", "/Cargo.toml", "/README.md", "/LICENSE", "/NOTICE", "/licenses/**"]

[dependencies]
tsr_tspath = { version = "0.1.0", path = "../tsr_tspath" }
tsr_jsstring = { version = "0.1.0", path = "../tsr_jsstring" }

[lints]
workspace = true
