[package]
name = "tsr_vfs"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
tsr_tspath = { version = "0.1.0", path = "../tsr_tspath" }
tsr_jsstring = { version = "0.1.0", path = "../tsr_jsstring" }

[lints]
workspace = true
