//! The rule table (`format/rules.go`). The three lists are a mechanical
//! translation of upstream's literal, in its order: that order, together with
//! the bucketing in `rulesmap`, decides which rule wins.

use crate::{
    rule::{action, rule, Predicate as P, RuleFlags, RuleSpec, TokenRange},
    rulecontext as c,
    settings::SemicolonPreference,
};
use tsr_ast::SyntaxKind as K;

fn kinds(first: K, last: K) -> impl Iterator<Item = K> {
    (first as u16..=last as u16).filter_map(K::from_u16)
}

// port: tsc/internal/format/rules.go:tokenRangeFrom
fn token_range_from(tokens: Vec<K>) -> TokenRange {
    TokenRange {
        tokens,
        is_specific: true,
    }
}

// port: tsc/internal/format/rules.go:tokenRangeFromRange
fn token_range_from_range(first: K, last: K) -> TokenRange {
    token_range_from(kinds(first, last).collect())
}

// port: tsc/internal/format/rules.go:getAllRules
#[allow(clippy::too_many_lines)]
pub(crate) fn get_all_rules() -> Vec<RuleSpec> {
    let all_tokens: Vec<K> = kinds(K::FirstToken, K::LastToken)
        .filter(|&token| token != K::EndOfFile)
        .collect();
    let any_token_except = |excluded: &[K]| TokenRange {
        tokens: all_tokens
            .iter()
            .copied()
            .filter(|token| !excluded.contains(token))
            .collect(),
        is_specific: false,
    };
    let any_token = TokenRange {
        tokens: all_tokens.clone(),
        is_specific: false,
    };
    // port: tsc/internal/format/rules.go:tokenRangeFromEx
    // Upstream builds both of these by appending to `allTokens`, which was
    // allocated with room for exactly one more element. The two appends write
    // the same slot of the shared backing array, so the first range does not
    // end in the multi-line comment kind it asked for: both end in
    // `EndOfFile`. The all-tokens prefix already holds the comment kind, so
    // only the bucket contents show the difference, and they are compared.
    let with_end_of_file = || {
        let mut tokens = all_tokens.clone();
        tokens.push(K::EndOfFile);
        token_range_from(tokens)
    };
    let any_token_including_multiline_comments = with_end_of_file();
    let any_token_including_eof = with_end_of_file();
    let keywords = token_range_from_range(K::FirstKeyword, K::LastKeyword);
    let binary_operators = token_range_from_range(K::FirstBinaryOperator, K::LastBinaryOperator);
    let binary_keyword_operators = token_range_from(vec![
        K::InKeyword,
        K::InstanceOfKeyword,
        K::OfKeyword,
        K::AsKeyword,
        K::IsKeyword,
        K::SatisfiesKeyword,
    ]);
    let unary_prefix_operators = token_range_from(vec![
        K::PlusPlusToken,
        K::MinusToken,
        K::TildeToken,
        K::ExclamationToken,
    ]);
    let unary_prefix_expressions = token_range_from(vec![
        K::NumericLiteral,
        K::BigIntLiteral,
        K::Identifier,
        K::OpenParenToken,
        K::OpenBracketToken,
        K::OpenBraceToken,
        K::ThisKeyword,
        K::NewKeyword,
    ]);
    let unary_preincrement_expressions = token_range_from(vec![
        K::Identifier,
        K::OpenParenToken,
        K::ThisKeyword,
        K::NewKeyword,
    ]);
    let unary_postincrement_expressions = token_range_from(vec![
        K::Identifier,
        K::CloseParenToken,
        K::CloseBracketToken,
        K::NewKeyword,
    ]);
    let unary_predecrement_expressions = unary_preincrement_expressions.clone();
    let unary_postdecrement_expressions = unary_postincrement_expressions.clone();
    let comments = token_range_from(vec![K::SingleLineCommentTrivia, K::MultiLineCommentTrivia]);
    let type_keywords = [
        K::AnyKeyword,
        K::AssertsKeyword,
        K::BigIntKeyword,
        K::BooleanKeyword,
        K::FalseKeyword,
        K::InferKeyword,
        K::KeyOfKeyword,
        K::NeverKeyword,
        K::NullKeyword,
        K::NumberKeyword,
        K::ObjectKeyword,
        K::ReadonlyKeyword,
        K::StringKeyword,
        K::SymbolKeyword,
        K::TypeOfKeyword,
        K::TrueKeyword,
        K::VoidKeyword,
        K::UndefinedKeyword,
        K::UniqueKeyword,
        K::UnknownKeyword,
    ];
    let type_names = token_range_from(
        std::iter::once(K::Identifier)
            .chain(type_keywords)
            .collect(),
    );

    // A space before the open brace of a function declaration. A function can
    // have a return type, which can be made of many token kinds.
    let function_open_brace_left_token_range = any_token_including_multiline_comments.clone();
    // A space before the open brace of a TypeScript declaration that has braces
    // as children: a class, a module, an enum and so on.
    let typescript_open_brace_left_token_range = token_range_from(vec![
        K::Identifier,
        K::GreaterThanToken,
        K::MultiLineCommentTrivia,
        K::ClassKeyword,
        K::ExportKeyword,
        K::ImportKeyword,
    ]);
    // A space before the open brace of a control flow construct.
    let control_open_brace_left_token_range = token_range_from(vec![
        K::CloseParenToken,
        K::MultiLineCommentTrivia,
        K::DoKeyword,
        K::TryKeyword,
        K::FinallyKeyword,
        K::ElseKeyword,
        K::CatchKeyword,
    ]);

    let high_priority_common_rules = vec![
        rule(
            "IgnoreBeforeComment",
            any_token.clone(),
            comments.clone(),
            vec![],
            action::STOP_PROCESSING_SPACE_ACTIONS,
            RuleFlags::None,
        ),
        rule(
            "IgnoreAfterLineComment",
            K::SingleLineCommentTrivia,
            any_token.clone(),
            vec![],
            action::STOP_PROCESSING_SPACE_ACTIONS,
            RuleFlags::None,
        ),
        rule(
            "NotSpaceBeforeColon",
            any_token.clone(),
            K::ColonToken,
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_not_binary_op_context),
                P::Fn(c::is_not_type_annotation_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterColon",
            K::ColonToken,
            any_token.clone(),
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_not_binary_op_context),
                P::Fn(c::is_next_token_parent_not_jsx_namespaced_name),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceBeforeQuestionMark",
            any_token.clone(),
            K::QuestionToken,
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_not_binary_op_context),
                P::Fn(c::is_not_type_annotation_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterQuestionMarkInConditionalOperator",
            K::QuestionToken,
            any_token.clone(),
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_conditional_operator_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceAfterQuestionMark",
            K::QuestionToken,
            any_token.clone(),
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_non_optional_property_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceBeforeDot",
            any_token.clone(),
            [K::DotToken, K::QuestionDotToken],
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_not_property_access_on_integer_literal),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceAfterDot",
            [K::DotToken, K::QuestionDotToken],
            any_token.clone(),
            vec![P::Fn(c::is_non_jsx_same_line_token_context)],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceBetweenImportParenInImportType",
            K::ImportKeyword,
            K::OpenParenToken,
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_import_type_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceAfterUnaryPrefixOperator",
            unary_prefix_operators.clone(),
            unary_prefix_expressions.clone(),
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_not_binary_op_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceAfterUnaryPreincrementOperator",
            K::PlusPlusToken,
            unary_preincrement_expressions.clone(),
            vec![P::Fn(c::is_non_jsx_same_line_token_context)],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceAfterUnaryPredecrementOperator",
            K::MinusMinusToken,
            unary_predecrement_expressions.clone(),
            vec![P::Fn(c::is_non_jsx_same_line_token_context)],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceBeforeUnaryPostincrementOperator",
            unary_postincrement_expressions.clone(),
            K::PlusPlusToken,
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_not_statement_condition_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceBeforeUnaryPostdecrementOperator",
            unary_postdecrement_expressions.clone(),
            K::MinusMinusToken,
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_not_statement_condition_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterPostincrementWhenFollowedByAdd",
            K::PlusPlusToken,
            K::PlusToken,
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_binary_op_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterAddWhenFollowedByUnaryPlus",
            K::PlusToken,
            K::PlusToken,
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_binary_op_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterAddWhenFollowedByPreincrement",
            K::PlusToken,
            K::PlusPlusToken,
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_binary_op_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterPostdecrementWhenFollowedBySubtract",
            K::MinusMinusToken,
            K::MinusToken,
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_binary_op_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterSubtractWhenFollowedByUnaryMinus",
            K::MinusToken,
            K::MinusToken,
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_binary_op_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterSubtractWhenFollowedByPredecrement",
            K::MinusToken,
            K::MinusMinusToken,
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_binary_op_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceAfterCloseBrace",
            K::CloseBraceToken,
            [K::CommaToken, K::SemicolonToken],
            vec![P::Fn(c::is_non_jsx_same_line_token_context)],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NewLineBeforeCloseBraceInBlockContext",
            any_token_including_multiline_comments.clone(),
            K::CloseBraceToken,
            vec![P::Fn(c::is_multiline_block_context)],
            action::INSERT_NEW_LINE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterCloseBrace",
            K::CloseBraceToken,
            any_token_except(&[K::CloseParenToken]),
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_after_code_block_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceBetweenCloseBraceAndElse",
            K::CloseBraceToken,
            K::ElseKeyword,
            vec![P::Fn(c::is_non_jsx_same_line_token_context)],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceBetweenCloseBraceAndWhile",
            K::CloseBraceToken,
            K::WhileKeyword,
            vec![P::Fn(c::is_non_jsx_same_line_token_context)],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceBetweenEmptyBraceBrackets",
            K::OpenBraceToken,
            K::CloseBraceToken,
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_object_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterConditionalClosingParen",
            K::CloseParenToken,
            K::OpenBracketToken,
            vec![P::Fn(c::is_control_decl_context)],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceBetweenFunctionKeywordAndStar",
            K::FunctionKeyword,
            K::AsteriskToken,
            vec![P::Fn(
                c::is_function_declaration_or_function_expression_context,
            )],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterStarInGeneratorDeclaration",
            K::AsteriskToken,
            K::Identifier,
            vec![P::Fn(
                c::is_function_declaration_or_function_expression_context,
            )],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterFunctionInFuncDecl",
            K::FunctionKeyword,
            any_token.clone(),
            vec![P::Fn(c::is_function_decl_context)],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NewLineAfterOpenBraceInBlockContext",
            K::OpenBraceToken,
            any_token.clone(),
            vec![P::Fn(c::is_multiline_block_context)],
            action::INSERT_NEW_LINE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterGetSetInMember",
            [K::GetKeyword, K::SetKeyword],
            K::Identifier,
            vec![P::Fn(c::is_function_decl_context)],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceBetweenYieldKeywordAndStar",
            K::YieldKeyword,
            K::AsteriskToken,
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_yield_or_yield_star_with_operand),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceBetweenYieldOrYieldStarAndOperand",
            [K::YieldKeyword, K::AsteriskToken],
            any_token.clone(),
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_yield_or_yield_star_with_operand),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceBetweenReturnAndSemicolon",
            K::ReturnKeyword,
            K::SemicolonToken,
            vec![P::Fn(c::is_non_jsx_same_line_token_context)],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterCertainKeywords",
            [
                K::VarKeyword,
                K::ThrowKeyword,
                K::NewKeyword,
                K::DeleteKeyword,
                K::ReturnKeyword,
                K::TypeOfKeyword,
                K::AwaitKeyword,
            ],
            any_token.clone(),
            vec![P::Fn(c::is_non_jsx_same_line_token_context)],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterLetConstInVariableDeclaration",
            [K::LetKeyword, K::ConstKeyword],
            any_token.clone(),
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_start_of_variable_declaration_list),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceBeforeOpenParenInFuncCall",
            any_token.clone(),
            K::OpenParenToken,
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_function_call_or_new_context),
                P::Fn(c::is_previous_token_not_comma),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceBeforeBinaryKeywordOperator",
            any_token.clone(),
            binary_keyword_operators.clone(),
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_binary_op_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterBinaryKeywordOperator",
            binary_keyword_operators.clone(),
            any_token.clone(),
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_binary_op_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterVoidOperator",
            K::VoidKeyword,
            any_token.clone(),
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_void_op_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceBetweenAsyncAndOpenParen",
            K::AsyncKeyword,
            K::OpenParenToken,
            vec![
                P::Fn(c::is_arrow_function_context),
                P::Fn(c::is_non_jsx_same_line_token_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceBetweenAsyncAndFunctionKeyword",
            K::AsyncKeyword,
            [K::FunctionKeyword, K::Identifier],
            vec![P::Fn(c::is_non_jsx_same_line_token_context)],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceBetweenTagAndTemplateString",
            [K::Identifier, K::CloseParenToken],
            [K::NoSubstitutionTemplateLiteral, K::TemplateHead],
            vec![P::Fn(c::is_non_jsx_same_line_token_context)],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceBeforeJsxAttribute",
            any_token.clone(),
            K::Identifier,
            vec![
                P::Fn(c::is_next_token_parent_jsx_attribute),
                P::Fn(c::is_non_jsx_same_line_token_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceBeforeSlashInJsxOpeningElement",
            any_token.clone(),
            K::SlashToken,
            vec![
                P::Fn(c::is_jsx_self_closing_element_context),
                P::Fn(c::is_non_jsx_same_line_token_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceBeforeGreaterThanTokenInJsxOpeningElement",
            K::SlashToken,
            K::GreaterThanToken,
            vec![
                P::Fn(c::is_jsx_self_closing_element_context),
                P::Fn(c::is_non_jsx_same_line_token_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceBeforeEqualInJsxAttribute",
            any_token.clone(),
            K::EqualsToken,
            vec![
                P::Fn(c::is_jsx_attribute_context),
                P::Fn(c::is_non_jsx_same_line_token_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceAfterEqualInJsxAttribute",
            K::EqualsToken,
            any_token.clone(),
            vec![
                P::Fn(c::is_jsx_attribute_context),
                P::Fn(c::is_non_jsx_same_line_token_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceBeforeJsxNamespaceColon",
            K::Identifier,
            K::ColonToken,
            vec![P::Fn(c::is_next_token_parent_jsx_namespaced_name)],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceAfterJsxNamespaceColon",
            K::ColonToken,
            K::Identifier,
            vec![P::Fn(c::is_next_token_parent_jsx_namespaced_name)],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceAfterModuleImport",
            [K::ModuleKeyword, K::RequireKeyword],
            K::OpenParenToken,
            vec![P::Fn(c::is_non_jsx_same_line_token_context)],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterCertainTypeScriptKeywords",
            [
                K::AbstractKeyword,
                K::AccessorKeyword,
                K::ClassKeyword,
                K::DeclareKeyword,
                K::DefaultKeyword,
                K::EnumKeyword,
                K::ExportKeyword,
                K::ExtendsKeyword,
                K::GetKeyword,
                K::ImplementsKeyword,
                K::ImportKeyword,
                K::InterfaceKeyword,
                K::ModuleKeyword,
                K::NamespaceKeyword,
                K::OverrideKeyword,
                K::PrivateKeyword,
                K::PublicKeyword,
                K::ProtectedKeyword,
                K::ReadonlyKeyword,
                K::SetKeyword,
                K::StaticKeyword,
                K::TypeKeyword,
                K::FromKeyword,
                K::KeyOfKeyword,
                K::InferKeyword,
            ],
            any_token.clone(),
            vec![P::Fn(c::is_non_jsx_same_line_token_context)],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceBeforeCertainTypeScriptKeywords",
            any_token.clone(),
            [K::ExtendsKeyword, K::ImplementsKeyword, K::FromKeyword],
            vec![P::Fn(c::is_non_jsx_same_line_token_context)],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterModuleName",
            K::StringLiteral,
            K::OpenBraceToken,
            vec![P::Fn(c::is_module_decl_context)],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceBeforeArrow",
            any_token.clone(),
            K::EqualsGreaterThanToken,
            vec![P::Fn(c::is_non_jsx_same_line_token_context)],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterArrow",
            K::EqualsGreaterThanToken,
            any_token.clone(),
            vec![P::Fn(c::is_non_jsx_same_line_token_context)],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceAfterEllipsis",
            K::DotDotDotToken,
            K::Identifier,
            vec![P::Fn(c::is_non_jsx_same_line_token_context)],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceAfterOptionalParameters",
            K::QuestionToken,
            [K::CloseParenToken, K::CommaToken],
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_not_binary_op_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceBetweenEmptyInterfaceBraceBrackets",
            K::OpenBraceToken,
            K::CloseBraceToken,
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_object_type_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceBeforeOpenAngularBracket",
            type_names.clone(),
            K::LessThanToken,
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_type_argument_or_parameter_or_assertion_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceBetweenCloseParenAndAngularBracket",
            K::CloseParenToken,
            K::LessThanToken,
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_type_argument_or_parameter_or_assertion_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceAfterOpenAngularBracket",
            K::LessThanToken,
            any_token.clone(),
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_type_argument_or_parameter_or_assertion_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceBeforeCloseAngularBracket",
            any_token.clone(),
            K::GreaterThanToken,
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_type_argument_or_parameter_or_assertion_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceAfterCloseAngularBracket",
            K::GreaterThanToken,
            [
                K::OpenParenToken,
                K::OpenBracketToken,
                K::GreaterThanToken,
                K::CommaToken,
            ],
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_type_argument_or_parameter_or_assertion_context),
                P::Fn(c::is_not_function_decl_context),
                P::Fn(c::is_non_type_assertion_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceBeforeAt",
            [K::CloseParenToken, K::Identifier],
            K::AtToken,
            vec![P::Fn(c::is_non_jsx_same_line_token_context)],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceAfterAt",
            K::AtToken,
            any_token.clone(),
            vec![P::Fn(c::is_non_jsx_same_line_token_context)],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterDecorator",
            any_token.clone(),
            [
                K::AbstractKeyword,
                K::Identifier,
                K::ExportKeyword,
                K::DefaultKeyword,
                K::ClassKeyword,
                K::StaticKeyword,
                K::PublicKeyword,
                K::PrivateKeyword,
                K::ProtectedKeyword,
                K::GetKeyword,
                K::SetKeyword,
                K::OpenBracketToken,
                K::AsteriskToken,
            ],
            vec![P::Fn(c::is_end_of_decorator_context_on_same_line)],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceBeforeNonNullAssertionOperator",
            any_token.clone(),
            K::ExclamationToken,
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_non_null_assertion_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceAfterNewKeywordOnConstructorSignature",
            K::NewKeyword,
            K::OpenParenToken,
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_constructor_signature_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceLessThanAndNonJSXTypeAnnotation",
            K::LessThanToken,
            K::LessThanToken,
            vec![P::Fn(c::is_non_jsx_same_line_token_context)],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
    ];
    let user_configurable_rules = vec![
        rule(
            "SpaceAfterConstructor",
            K::ConstructorKeyword,
            K::OpenParenToken,
            vec![
                P::OptionEnabled(|o| o.insert_space_after_constructor),
                P::Fn(c::is_non_jsx_same_line_token_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceAfterConstructor",
            K::ConstructorKeyword,
            K::OpenParenToken,
            vec![
                P::OptionDisabledOrUndefined(|o| o.insert_space_after_constructor),
                P::Fn(c::is_non_jsx_same_line_token_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterComma",
            K::CommaToken,
            any_token.clone(),
            vec![
                P::OptionEnabled(|o| o.insert_space_after_comma_delimiter),
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_non_jsx_element_or_fragment_context),
                P::Fn(c::is_next_token_not_close_bracket),
                P::Fn(c::is_next_token_not_close_paren),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceAfterComma",
            K::CommaToken,
            any_token.clone(),
            vec![
                P::OptionDisabledOrUndefined(|o| o.insert_space_after_comma_delimiter),
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_non_jsx_element_or_fragment_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterAnonymousFunctionKeyword",
            [K::FunctionKeyword, K::AsteriskToken],
            K::OpenParenToken,
            vec![
                P::OptionEnabled(|o| o.insert_space_after_function_keyword_for_anonymous_functions),
                P::Fn(c::is_function_decl_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceAfterAnonymousFunctionKeyword",
            [K::FunctionKeyword, K::AsteriskToken],
            K::OpenParenToken,
            vec![
                P::OptionDisabledOrUndefined(|o| {
                    o.insert_space_after_function_keyword_for_anonymous_functions
                }),
                P::Fn(c::is_function_decl_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterKeywordInControl",
            keywords.clone(),
            K::OpenParenToken,
            vec![
                P::OptionEnabled(|o| o.insert_space_after_keywords_in_control_flow_statements),
                P::Fn(c::is_control_decl_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceAfterKeywordInControl",
            keywords.clone(),
            K::OpenParenToken,
            vec![
                P::OptionDisabledOrUndefined(|o| {
                    o.insert_space_after_keywords_in_control_flow_statements
                }),
                P::Fn(c::is_control_decl_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterOpenParen",
            K::OpenParenToken,
            any_token.clone(),
            vec![
                P::OptionEnabled(|o| {
                    o.insert_space_after_opening_and_before_closing_nonempty_parenthesis
                }),
                P::Fn(c::is_non_jsx_same_line_token_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceBeforeCloseParen",
            any_token.clone(),
            K::CloseParenToken,
            vec![
                P::OptionEnabled(|o| {
                    o.insert_space_after_opening_and_before_closing_nonempty_parenthesis
                }),
                P::Fn(c::is_non_jsx_same_line_token_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceBetweenOpenParens",
            K::OpenParenToken,
            K::OpenParenToken,
            vec![
                P::OptionEnabled(|o| {
                    o.insert_space_after_opening_and_before_closing_nonempty_parenthesis
                }),
                P::Fn(c::is_non_jsx_same_line_token_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceBetweenParens",
            K::OpenParenToken,
            K::CloseParenToken,
            vec![P::Fn(c::is_non_jsx_same_line_token_context)],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceAfterOpenParen",
            K::OpenParenToken,
            any_token.clone(),
            vec![
                P::OptionDisabledOrUndefined(|o| {
                    o.insert_space_after_opening_and_before_closing_nonempty_parenthesis
                }),
                P::Fn(c::is_non_jsx_same_line_token_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceBeforeCloseParen",
            any_token.clone(),
            K::CloseParenToken,
            vec![
                P::OptionDisabledOrUndefined(|o| {
                    o.insert_space_after_opening_and_before_closing_nonempty_parenthesis
                }),
                P::Fn(c::is_non_jsx_same_line_token_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterOpenBracket",
            K::OpenBracketToken,
            any_token.clone(),
            vec![
                P::OptionEnabled(|o| {
                    o.insert_space_after_opening_and_before_closing_nonempty_brackets
                }),
                P::Fn(c::is_non_jsx_same_line_token_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceBeforeCloseBracket",
            any_token.clone(),
            K::CloseBracketToken,
            vec![
                P::OptionEnabled(|o| {
                    o.insert_space_after_opening_and_before_closing_nonempty_brackets
                }),
                P::Fn(c::is_non_jsx_same_line_token_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceBetweenBrackets",
            K::OpenBracketToken,
            K::CloseBracketToken,
            vec![P::Fn(c::is_non_jsx_same_line_token_context)],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceAfterOpenBracket",
            K::OpenBracketToken,
            any_token.clone(),
            vec![
                P::OptionDisabledOrUndefined(|o| {
                    o.insert_space_after_opening_and_before_closing_nonempty_brackets
                }),
                P::Fn(c::is_non_jsx_same_line_token_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceBeforeCloseBracket",
            any_token.clone(),
            K::CloseBracketToken,
            vec![
                P::OptionDisabledOrUndefined(|o| {
                    o.insert_space_after_opening_and_before_closing_nonempty_brackets
                }),
                P::Fn(c::is_non_jsx_same_line_token_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterOpenBrace",
            K::OpenBraceToken,
            any_token.clone(),
            vec![
                P::OptionEnabledOrUndefined(|o| {
                    o.insert_space_after_opening_and_before_closing_nonempty_braces
                }),
                P::Fn(c::is_brace_wrapped_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceBeforeCloseBrace",
            any_token.clone(),
            K::CloseBraceToken,
            vec![
                P::OptionEnabledOrUndefined(|o| {
                    o.insert_space_after_opening_and_before_closing_nonempty_braces
                }),
                P::Fn(c::is_brace_wrapped_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceBetweenEmptyBraceBrackets",
            K::OpenBraceToken,
            K::CloseBraceToken,
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_object_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceAfterOpenBrace",
            K::OpenBraceToken,
            any_token.clone(),
            vec![
                P::OptionDisabled(|o| {
                    o.insert_space_after_opening_and_before_closing_nonempty_braces
                }),
                P::Fn(c::is_non_jsx_same_line_token_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceBeforeCloseBrace",
            any_token.clone(),
            K::CloseBraceToken,
            vec![
                P::OptionDisabled(|o| {
                    o.insert_space_after_opening_and_before_closing_nonempty_braces
                }),
                P::Fn(c::is_non_jsx_same_line_token_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceBetweenEmptyBraceBrackets",
            K::OpenBraceToken,
            K::CloseBraceToken,
            vec![P::OptionEnabled(|o| {
                o.insert_space_after_opening_and_before_closing_empty_braces
            })],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceBetweenEmptyBraceBrackets",
            K::OpenBraceToken,
            K::CloseBraceToken,
            vec![
                P::OptionDisabled(|o| o.insert_space_after_opening_and_before_closing_empty_braces),
                P::Fn(c::is_non_jsx_same_line_token_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterTemplateHeadAndMiddle",
            [K::TemplateHead, K::TemplateMiddle],
            any_token.clone(),
            vec![
                P::OptionEnabled(|o| {
                    o.insert_space_after_opening_and_before_closing_template_string_braces
                }),
                P::Fn(c::is_non_jsx_text_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::CanDeleteNewLines,
        ),
        rule(
            "SpaceBeforeTemplateMiddleAndTail",
            any_token.clone(),
            [K::TemplateMiddle, K::TemplateTail],
            vec![
                P::OptionEnabled(|o| {
                    o.insert_space_after_opening_and_before_closing_template_string_braces
                }),
                P::Fn(c::is_non_jsx_same_line_token_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceAfterTemplateHeadAndMiddle",
            [K::TemplateHead, K::TemplateMiddle],
            any_token.clone(),
            vec![
                P::OptionDisabledOrUndefined(|o| {
                    o.insert_space_after_opening_and_before_closing_template_string_braces
                }),
                P::Fn(c::is_non_jsx_text_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::CanDeleteNewLines,
        ),
        rule(
            "NoSpaceBeforeTemplateMiddleAndTail",
            any_token.clone(),
            [K::TemplateMiddle, K::TemplateTail],
            vec![
                P::OptionDisabledOrUndefined(|o| {
                    o.insert_space_after_opening_and_before_closing_template_string_braces
                }),
                P::Fn(c::is_non_jsx_same_line_token_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterOpenBraceInJsxExpression",
            K::OpenBraceToken,
            any_token.clone(),
            vec![
                P::OptionEnabled(|o| {
                    o.insert_space_after_opening_and_before_closing_jsx_expression_braces
                }),
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_jsx_expression_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceBeforeCloseBraceInJsxExpression",
            any_token.clone(),
            K::CloseBraceToken,
            vec![
                P::OptionEnabled(|o| {
                    o.insert_space_after_opening_and_before_closing_jsx_expression_braces
                }),
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_jsx_expression_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceAfterOpenBraceInJsxExpression",
            K::OpenBraceToken,
            any_token.clone(),
            vec![
                P::OptionDisabledOrUndefined(|o| {
                    o.insert_space_after_opening_and_before_closing_jsx_expression_braces
                }),
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_jsx_expression_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceBeforeCloseBraceInJsxExpression",
            any_token.clone(),
            K::CloseBraceToken,
            vec![
                P::OptionDisabledOrUndefined(|o| {
                    o.insert_space_after_opening_and_before_closing_jsx_expression_braces
                }),
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_jsx_expression_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterSemicolonInFor",
            K::SemicolonToken,
            any_token.clone(),
            vec![
                P::OptionEnabled(|o| o.insert_space_after_semicolon_in_for_statements),
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_for_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceAfterSemicolonInFor",
            K::SemicolonToken,
            any_token.clone(),
            vec![
                P::OptionDisabledOrUndefined(|o| o.insert_space_after_semicolon_in_for_statements),
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_for_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceBeforeBinaryOperator",
            any_token.clone(),
            binary_operators.clone(),
            vec![
                P::OptionEnabled(|o| o.insert_space_before_and_after_binary_operators),
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_binary_op_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterBinaryOperator",
            binary_operators.clone(),
            any_token.clone(),
            vec![
                P::OptionEnabled(|o| o.insert_space_before_and_after_binary_operators),
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_binary_op_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceBeforeBinaryOperator",
            any_token.clone(),
            binary_operators.clone(),
            vec![
                P::OptionDisabledOrUndefined(|o| o.insert_space_before_and_after_binary_operators),
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_binary_op_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceAfterBinaryOperator",
            binary_operators.clone(),
            any_token.clone(),
            vec![
                P::OptionDisabledOrUndefined(|o| o.insert_space_before_and_after_binary_operators),
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_binary_op_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceBeforeOpenParenInFuncDecl",
            any_token.clone(),
            K::OpenParenToken,
            vec![
                P::OptionEnabled(|o| o.insert_space_before_function_parenthesis),
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_function_decl_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceBeforeOpenParenInFuncDecl",
            any_token.clone(),
            K::OpenParenToken,
            vec![
                P::OptionDisabledOrUndefined(|o| o.insert_space_before_function_parenthesis),
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_function_decl_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NewLineBeforeOpenBraceInControl",
            control_open_brace_left_token_range.clone(),
            K::OpenBraceToken,
            vec![
                P::OptionEnabled(|o| o.place_open_brace_on_new_line_for_control_blocks),
                P::Fn(c::is_control_decl_context),
                P::Fn(c::is_before_multiline_block_context),
            ],
            action::INSERT_NEW_LINE,
            RuleFlags::CanDeleteNewLines,
        ),
        rule(
            "NewLineBeforeOpenBraceInFunction",
            function_open_brace_left_token_range.clone(),
            K::OpenBraceToken,
            vec![
                P::OptionEnabled(|o| o.place_open_brace_on_new_line_for_functions),
                P::Fn(c::is_function_decl_context),
                P::Fn(c::is_before_multiline_block_context),
            ],
            action::INSERT_NEW_LINE,
            RuleFlags::CanDeleteNewLines,
        ),
        rule(
            "NewLineBeforeOpenBraceInTypeScriptDeclWithBlock",
            typescript_open_brace_left_token_range.clone(),
            K::OpenBraceToken,
            vec![
                P::OptionEnabled(|o| o.place_open_brace_on_new_line_for_functions),
                P::Fn(c::is_typescript_decl_with_block_context),
                P::Fn(c::is_before_multiline_block_context),
            ],
            action::INSERT_NEW_LINE,
            RuleFlags::CanDeleteNewLines,
        ),
        rule(
            "SpaceAfterTypeAssertion",
            K::GreaterThanToken,
            any_token.clone(),
            vec![
                P::OptionEnabled(|o| o.insert_space_after_type_assertion),
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_type_assertion_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceAfterTypeAssertion",
            K::GreaterThanToken,
            any_token.clone(),
            vec![
                P::OptionDisabledOrUndefined(|o| o.insert_space_after_type_assertion),
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_type_assertion_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceBeforeTypeAnnotation",
            any_token.clone(),
            [K::QuestionToken, K::ColonToken],
            vec![
                P::OptionEnabled(|o| o.insert_space_before_type_annotation),
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_type_annotation_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceBeforeTypeAnnotation",
            any_token.clone(),
            [K::QuestionToken, K::ColonToken],
            vec![
                P::OptionDisabledOrUndefined(|o| o.insert_space_before_type_annotation),
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_type_annotation_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoOptionalSemicolon",
            K::SemicolonToken,
            any_token_including_eof.clone(),
            vec![
                P::SemicolonEquals(SemicolonPreference::Remove),
                P::Fn(c::is_semicolon_deletion_context),
            ],
            action::DELETE_TOKEN,
            RuleFlags::None,
        ),
        rule(
            "OptionalSemicolon",
            any_token.clone(),
            any_token_including_eof.clone(),
            vec![
                P::SemicolonEquals(SemicolonPreference::Insert),
                P::Fn(c::is_semicolon_insertion_context),
            ],
            action::INSERT_TRAILING_SEMICOLON,
            RuleFlags::None,
        ),
    ];
    let low_priority_common_rules = vec![
        rule(
            "NoSpaceBeforeSemicolon",
            any_token.clone(),
            K::SemicolonToken,
            vec![P::Fn(c::is_non_jsx_same_line_token_context)],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceBeforeOpenBraceInControl",
            control_open_brace_left_token_range.clone(),
            K::OpenBraceToken,
            vec![
                P::OptionDisabledOrUndefinedOrTokensOnSameLine(|o| {
                    o.place_open_brace_on_new_line_for_control_blocks
                }),
                P::Fn(c::is_control_decl_context),
                P::Fn(c::is_not_format_on_enter),
                P::Fn(c::is_same_line_token_or_before_block_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::CanDeleteNewLines,
        ),
        rule(
            "SpaceBeforeOpenBraceInFunction",
            function_open_brace_left_token_range.clone(),
            K::OpenBraceToken,
            vec![
                P::OptionDisabledOrUndefinedOrTokensOnSameLine(|o| {
                    o.place_open_brace_on_new_line_for_functions
                }),
                P::Fn(c::is_function_decl_context),
                P::Fn(c::is_before_block_context),
                P::Fn(c::is_not_format_on_enter),
                P::Fn(c::is_same_line_token_or_before_block_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::CanDeleteNewLines,
        ),
        rule(
            "SpaceBeforeOpenBraceInTypeScriptDeclWithBlock",
            typescript_open_brace_left_token_range.clone(),
            K::OpenBraceToken,
            vec![
                P::OptionDisabledOrUndefinedOrTokensOnSameLine(|o| {
                    o.place_open_brace_on_new_line_for_functions
                }),
                P::Fn(c::is_typescript_decl_with_block_context),
                P::Fn(c::is_not_format_on_enter),
                P::Fn(c::is_same_line_token_or_before_block_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::CanDeleteNewLines,
        ),
        rule(
            "NoSpaceBeforeComma",
            any_token.clone(),
            K::CommaToken,
            vec![P::Fn(c::is_non_jsx_same_line_token_context)],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceBeforeOpenBracket",
            any_token_except(&[K::AsyncKeyword, K::CaseKeyword]),
            K::OpenBracketToken,
            vec![P::Fn(c::is_non_jsx_same_line_token_context)],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "NoSpaceAfterCloseBracket",
            K::CloseBracketToken,
            any_token.clone(),
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_not_before_block_in_function_declaration_context),
            ],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterSemicolon",
            K::SemicolonToken,
            any_token.clone(),
            vec![P::Fn(c::is_non_jsx_same_line_token_context)],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceBetweenForAndAwaitKeyword",
            K::ForKeyword,
            K::AwaitKeyword,
            vec![P::Fn(c::is_non_jsx_same_line_token_context)],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceBetweenDotDotDotAndTypeName",
            K::DotDotDotToken,
            type_names.clone(),
            vec![P::Fn(c::is_non_jsx_same_line_token_context)],
            action::DELETE_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceBetweenStatements",
            [
                K::CloseParenToken,
                K::DoKeyword,
                K::ElseKeyword,
                K::CaseKeyword,
            ],
            any_token.clone(),
            vec![
                P::Fn(c::is_non_jsx_same_line_token_context),
                P::Fn(c::is_non_jsx_element_or_fragment_context),
                P::Fn(c::is_not_for_context),
            ],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
        rule(
            "SpaceAfterTryCatchFinally",
            [K::TryKeyword, K::CatchKeyword, K::FinallyKeyword],
            K::OpenBraceToken,
            vec![P::Fn(c::is_non_jsx_same_line_token_context)],
            action::INSERT_SPACE,
            RuleFlags::None,
        ),
    ];

    let mut result = high_priority_common_rules;
    result.extend(user_configurable_rules);
    result.extend(low_priority_common_rules);
    result
}
