package main

import (
	"fmt"
	"sort"
	"unicode"
)

func main() {
	names := []string{}
	for n := range unicode.Categories {
		names = append(names, n)
	}
	for n := range unicode.Scripts {
		names = append(names, n)
	}
	sort.Strings(names)
	fmt.Println("// Generated by tools/phase5/regexp-unicode.go from pinned Go Unicode", unicode.Version, ".\n// RE2 property names and ranges; the Rust regex engine's Unicode version is not authority.\n#[allow(clippy::unreadable_literal, reason = \"Numeric range table emitted directly from Go Unicode\")]\n#[rustfmt::skip]\npub(super) const PROPERTIES: &[(&str, &[(u32,u32)])] = &[")
	for _, n := range names {
		t := unicode.Categories[n]
		if t == nil {
			t = unicode.Scripts[n]
		}
		fmt.Printf("(%q,&[", n)
		for _, r := range t.R16 {
			emit(uint32(r.Lo), uint32(r.Hi), uint32(r.Stride))
		}
		for _, r := range t.R32 {
			emit(r.Lo, r.Hi, r.Stride)
		}
		fmt.Println("]),")
	}
	fmt.Println("];")
}
func emit(lo, hi, stride uint32) {
	if stride == 1 {
		fmt.Printf("(%d,%d),", lo, hi)
	} else {
		for r := lo; r <= hi; r += stride {
			fmt.Printf("(%d,%d),", r, r)
		}
	}
}
