// Generates the organize-imports collation data from the pinned Go toolchain
// and golang.org/x/text version. Run from upstream/tsc, with GOTOOLCHAIN=local:
// go run ../../tools/phase5/lsp/unicode.go > ../../crates/tsr_ls/src/organize_unicode.rs
package main

import (
	"bufio"
	"fmt"
	"golang.org/x/text/unicode/norm"
	"os"
	"runtime"
	"strconv"
	"unicode"
	"unicode/utf8"
)

func number(n rune) string {
	s := strconv.FormatInt(int64(n), 10)
	for at := len(s) - 3; at > 0; at -= 3 {
		s = s[:at] + "_" + s[at:]
	}
	return s
}

func main() {
	w := bufio.NewWriter(os.Stdout)
	defer w.Flush()
	fmt.Fprintf(w, "// Generated by tools/phase5/lsp/unicode.go with %s; Go Unicode %s, NFD Unicode %s.\n", runtime.Version(), unicode.Version, norm.Version)
	fmt.Fprintln(w, "// (rune, simple lowercase, canonical combining class, Mn, Lu).\n#[rustfmt::skip]\npub(super) const PROPERTIES: &[(u32, u32, u8, bool, bool)] = &[")
	for r := rune(0); r <= utf8.MaxRune; r++ {
		if !utf8.ValidRune(r) {
			continue
		}
		lower, ccc, mark, upper := unicode.ToLower(r), norm.NFD.PropertiesString(string(r)).CCC(), unicode.Is(unicode.Mn, r), unicode.IsUpper(r)
		if lower != r || ccc != 0 || mark || upper {
			fmt.Fprintf(w, "(%s,%s,%d,%t,%t),\n", number(r), number(lower), ccc, mark, upper)
		}
	}
	fmt.Fprintln(w, "];\n#[rustfmt::skip]\npub(super) const DECOMPOSITIONS: &[(u32, &[u32])] = &[")
	for r := rune(0); r <= utf8.MaxRune; r++ {
		if !utf8.ValidRune(r) || r >= 0xac00 && r <= 0xd7a3 {
			continue
		} // algorithmic Hangul
		s := norm.NFD.String(string(r))
		if s == string(r) {
			continue
		}
		fmt.Fprintf(w, "(%s,&[", number(r))
		for _, d := range s {
			fmt.Fprintf(w, "%s,", number(d))
		}
		fmt.Fprintln(w, "]),")
	}
	fmt.Fprintln(w, "];")
}
