[package]
name = "tsr_ipc"
version = "0.4.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = ["crates-io"]
description = "Bidirectional JSON-RPC connections for tsr"
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"
include = ["/src/**", "/Cargo.toml", "/README.md", "/LICENSE", "/NOTICE", "/licenses/**"]

[dependencies]
tsr_json = { version = "0.4.0", path = "../tsr_json" }
tsr_jsonrpc = { version = "0.4.0", path = "../tsr_jsonrpc" }

[lints]
workspace = true
