//! The locale leaf group.
//!
//! Nothing in the workspace parses a BCP 47 tag, canonicalises one, carries a
//! locale alongside a request, or selects a translation table: `tsr_diagnostics`
//! ships the English message identities and says so in its own header
//! ("Formatting, locale negotiation and diagnostic production belong to later
//! compiler slices"). So every subject here is a recorded gap.
//!
//! The gap is recorded rather than emulated on purpose. The whole point of
//! freezing these cases now is that F1b picks a Rust BCP 47 dependency *after*
//! the native observations exist; a driver that canonicalised tags itself, or
//! that answered the und case out of the English table, would be the very
//! substitute the plan forbids and would make the comparison agree with a
//! locale implementation nobody has written.

use crate::api::Outcome;
use serde_json::Value;

/// One row per subject this group's requests declare: the Go authority, the
/// intended Rust signature and the production home that has to exist before the
/// row can turn into an observation.
const MISSING: &[(&str, &str, &str, &str)] = &[
    (
        "locale.parse",
        "tsc/internal/locale/locale.go:36 Parse, over golang.org/x/text/language v0.38.0",
        "pub fn parse(tag: &str) -> (Locale, bool) -- the tag is returned even when the bool is false, because tsoptions/parsedcommandline.go:491 keeps it",
        "crates/tsr_locale/src/lib.rs (absent; no crate parses a language tag, and the dependency is chosen in F1b from these frozen cases)",
    ),
    (
        "locale.string",
        "tsc/internal/locale/locale.go:15 Locale.String",
        "impl Display for Locale -- the empty string for the Default sentinel, the canonical tag otherwise",
        "crates/tsr_locale/src/lib.rs (absent)",
    ),
    (
        "locale.context",
        "tsc/internal/locale/locale.go:22 WithLocale, :26 FromContext, :31 HasLocale",
        "a carrier that keeps `absent` distinct from `present and default`, mirroring session.go:1359; in Rust an explicit Option<Locale> parameter rather than a context value",
        "crates/tsr_locale/src/lib.rs (absent) plus the request plumbing in crates/tsr_project",
    ),
    (
        "locale.default",
        "tsc/internal/locale/locale.go:13 var Default Locale",
        "pub const DEFAULT: Locale -- the zero tag, equal to what an absent locale reads back as",
        "crates/tsr_locale/src/lib.rs (absent)",
    ),
    (
        "locale.translation",
        "tsc/internal/diagnostics/diagnostics.go:71 Localize and :89 getLocalizedMessages, over the 13 tables embedded by loc_generated.go",
        "pub fn localize(locale: &Locale, message: &'static Message, args: &[String]) -> String, selecting a table by language.NewMatcher confidence >= Low and falling back to the English text per key",
        "crates/tsr_diagnostics/src/localize.rs (absent) with tables generated by xtask/src/gen/diagnostics.rs (extension lands in F1b; see data/phase1/locale-assets.json)",
    ),
    (
        "locale.translation-args",
        "tsc/internal/diagnostics/diagnostics.go:67 Message.Localize and :117 Format",
        "pub fn localize_with(locale: &Locale, message: &'static Message, args: &[String]) -> String, substituting {0}.. into the *selected* template so a translation may reorder placeholders",
        "crates/tsr_diagnostics/src/localize.rs (absent); the shared formatting seam is owned with F3a, not duplicated in this driver",
    ),
    (
        "locale.translation-cache",
        "tsc/internal/diagnostics/diagnostics.go:87 localizedMessagesCache",
        "a process-lifetime table cache keyed by the requested tag, never invalidated, transparent to callers; Rust has no equivalent because no table is loaded at all",
        "crates/tsr_diagnostics/src/localize.rs (absent)",
    ),
];

// Reviewed entry points of the absent APIs above; the request must match
// both subject and identity before it can report a gap.
const MISSING_OPERATIONS: &[(&str, &str)] = &[
    ("locale.context", "tsc/internal/locale/locale.go:WithLocale"),
    (
        "locale.default",
        "tsc/internal/locale/locale.go:Locale.String",
    ),
    ("locale.parse", "tsc/internal/locale/locale.go:Parse"),
    (
        "locale.string",
        "tsc/internal/locale/locale.go:Locale.String",
    ),
    (
        "locale.translation",
        "tsc/internal/diagnostics/diagnostics.go:Localize",
    ),
    (
        "locale.translation",
        "tsc/internal/diagnostics/diagnostics.go:getLocalizedMessages",
    ),
    (
        "locale.translation-args",
        "tsc/internal/diagnostics/diagnostics.go:Message.Localize",
    ),
    (
        "locale.translation-cache",
        "tsc/internal/diagnostics/diagnostics.go:getLocalizedMessages",
    ),
];

pub fn observe(request: &Value) -> Option<Outcome> {
    let subject = crate::api::subject(request);
    MISSING.iter().find(|(name, _, _, _)| *name == subject).map(
        |(_, authority, signature, home)| {
            crate::api::missing_for_subject(request, MISSING_OPERATIONS, authority, signature, home)
        },
    )
}
