#!/usr/bin/env python3
"""Reproduce the pinned isKeywordOrPunctuation table, without editing the pin.

    PATH=/Users/cristian/.local/share/mise/installs/go/1.27.1/bin:$PATH \\
        python3 tools/phase1/parser-tokens/observe.py --output <new directory> [--write]

The overlay `export_test.go` runs in the pinned `internal/parser` package with
`requests.json`. Without `--write` the measured rows must equal the frozen
`native-observations.json` and the Rust table
`crates/tsr_parser/src/testdata/keyword_or_punctuation.rs`; `--write` replaces
both, and the provenance, after review. Go host metadata may differ across
hosts; the request, pinned source and rows must agree.
"""
import argparse
import json
from pathlib import Path
import shutil
import sys

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "scripts"))

import phase1_capture as capture  # noqa: E402
from s04_common import strict_json_loads  # noqa: E402

FIXTURE = ROOT / "tools/phase1/parser-tokens"
# A Rust module rather than a data file, so the table sits inside every
# closure that already takes the crate's Rust sources.
TABLE = ROOT / "crates/tsr_parser/src/testdata/keyword_or_punctuation.rs"
TEST = "TestPhase1KeywordOrPunctuation"


def table(observed):
    """The Rust table: (Kind, Go Kind.String(), isKeywordOrPunctuation) per row."""
    lines = ["//! Generated by tools/phase1/parser-tokens/observe.py from the pinned parser",
             "//! package's isKeywordOrPunctuation over every Kind from -1 through",
             f'//! KindCount+1 (KindCount = {observed["kind_count"]}); do not edit.',
             "",
             "pub(super) const TABLE: &[(i64, &str, bool)] = &["]
    for row in observed["observations"]:
        name = json.dumps(row["name"])
        lines.append(f'    ({row["kind"]}, {name}, {"true" if row["keyword_or_punctuation"] else "false"}),')
    lines.append("];")
    return "\n".join(lines) + "\n"


def observe(output, write=False):
    requests = strict_json_loads((FIXTURE / "requests.json").read_bytes())
    observed = capture.run_probe(output, "parser", (FIXTURE / "export_test.go").read_text(),
                                 requests, TEST, False)
    rendered = table(observed)
    (output / TABLE.name).write_text(rendered)
    frozen = FIXTURE / "native-observations.json"
    recorded = strict_json_loads(frozen.read_bytes()) if frozen.is_file() else {}
    equal = (recorded.get("observations") == observed["observations"]
             and recorded.get("kind_count") == observed["kind_count"]
             and TABLE.is_file() and TABLE.read_text() == rendered)
    if write:
        shutil.copyfile(output / "observations.json", frozen)
        shutil.copyfile(output / "provenance.json", FIXTURE / "native-provenance.json")
        TABLE.write_text(rendered)
    return {"match": equal, "kinds": len(observed["observations"]),
            "kind_count": observed["kind_count"], "output": str(output)}


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--output", type=Path, required=True, help="new, non-existing output directory")
    parser.add_argument("--write", action="store_true", help="replace the frozen observations and the Rust table")
    args = parser.parse_args()
    result = observe(args.output.resolve(), args.write)
    print(json.dumps(result, sort_keys=True))
    if not result["match"] and not args.write:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
