#!/usr/bin/env python3
"""Generate the CompilerOptions field table (declaration order, option flags) from the pinned Go.

The Rust ports of tsoptions/declscompiler.go and showconfig.go iterate the
fields of core.CompilerOptions the way the pinned Go reflects over them; this
table is that order, each field's reflect index and the flags of the option
declaration CommandLineCompilerOptionsMap finds for it.
"""
import argparse
import hashlib
import json
import shutil
from s04_common import command, strict_json_loads
from s06_build import ROOT, oracle_export

OUTPUT = ROOT / 'crates/tsr_tsoptions/src/option_fields_generated.rs'


def row(field):
    return ('OptionField {index:%d,field:%s,declaration:%s,affects_emit:%s,affects_declaration_path:%s,'
            'affects_semantic_diagnostics:%s,strict_flag:%s,allow_js_flag:%s,category:%s}' % (
                field['index'], json.dumps(field['field']), json.dumps(field['declaration']),
                str(field['affects_emit']).lower(), str(field['affects_declaration_path']).lower(),
                str(field['affects_semantic_diagnostics']).lower(), str(field['strict_flag']).lower(),
                str(field['allow_js_flag']).lower(), json.dumps(field['category'])))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    adapter = ROOT / 'tools/phase1/options/fields_test.go'
    with oracle_export() as (checkout, env, pin):
        package = checkout / 'tsc/internal/tsoptions'
        shutil.copyfile(adapter, package / 'phase1_fields_test.go')
        output = checkout / 'fields.json'
        env['PHASE1_OPTION_FIELDS_OUTPUT'] = str(output)
        # internal/repo panics under -trimpath unless its path has a prefix to trim.
        repo_path = f'-gcflags=github.com/microsoft/TypeScript/tsc/internal/repo=-trimpath={checkout}/phase1-unmatched-prefix'
        command(['go', 'test', '-trimpath', '-mod=readonly', repo_path, './internal/tsoptions', '-run',
                 '^TestPhase1OptionFields$', '-count=1'], cwd=checkout / 'tsc', env=env)
        fields = strict_json_loads(output.read_bytes())
    adapter_sha = hashlib.sha256(adapter.read_bytes()).hexdigest()
    rust = ('// Generated by scripts/phase1_option_fields.py from ' + pin + ' (adapter ' + adapter_sha[:16] + '). Do not edit.\n'
            'use super::OptionField;\n#[rustfmt::skip]\npub static COMPILER_OPTION_FIELDS: &[OptionField] = &[\n'
            + ',\n'.join(row(field) for field in fields) + '\n];\n')
    if args.write:
        OUTPUT.write_bytes(rust.encode())
    elif not OUTPUT.exists() or OUTPUT.read_bytes() != rust.encode():
        raise ValueError('option fields changed: ' + str(OUTPUT))
    print(len(fields), 'fields')


if __name__ == '__main__':
    main()
