#!/usr/bin/env python3
"""Write docs/PHASE6-tests.md: the pinned client's test cases by file from a
native run, and every pinned Go test of `internal/api` with its route."""
from __future__ import annotations
import argparse
from collections import Counter
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[3]
TEST = re.compile(r'^func (Test\w+)\(\w+ \*testing\.T\)', re.M)

# Reviewed routes: a Rust test that ports the observation, or the work that
# still owes it. A name here is a claim about assertions, not similarity.
ROUTES = {
    ('api', 'TestDocumentIdentifierUnmarshalJSON'):
        'crates/tsr_api/src/proto/tests.rs pinned_wire_fixtures_hold: the five document-identifier fixtures of the S03 export are the same inputs',
    ('api', 'TestJSONValueToAny'): 'WORK (A2 follow-up): the JSON value conversion of parseJsonConfigFileContent',
    ('api', 'TestStandaloneSessionUsesSnapshotHostWithoutProjectSession'):
        'crates/tsr_api/src/session/tests.rs a_standalone_session_updates_snapshots_over_its_own_project_session and create_program_builds_one_synthetic_project_from_explicit_roots (snapshot ids are not compared: the Rust counter is process-wide)',
    ('api', 'TestSessionTracksAndReleasesAPIRefs'):
        'crates/tsr_api/src/session/tests.rs project_opens_are_idempotent_and_closes_release_only_held_refs (the standalone session; the shared project session case is A3)',
    ('api', 'TestUpdateTemporarySnapshot'):
        'crates/tsr_api/src/session/tests.rs a_temporary_snapshot_overrides_one_file_without_advancing_the_latest (file text instead of semantic diagnostics until A4)',
    ('api', 'TestUpdateTemporarySnapshotRejectsUnsupportedExtension'):
        'crates/tsr_api/src/session/tests.rs a_temporary_snapshot_overrides_one_file_without_advancing_the_latest (the tail)',
    ('api', 'TestCreateProgram'):
        'crates/tsr_api/src/session/tests.rs create_program_builds_one_synthetic_project_from_explicit_roots (without semantic diagnostics until A4)',
    ('api', 'TestCreateProgramFileChangesRequireOldProgram'):
        'crates/tsr_api/src/session/tests.rs create_program_builds_one_synthetic_project_from_explicit_roots (the error text)',
    ('api', 'TestNewDiagnosticResponseIncludesFormattingContext'): 'WORK (A4): diagnostic responses',
    ('api', 'TestNewDiagnosticResponseTruncatesLongFormattingContext'): 'WORK (A4): diagnostic responses',
}
CHECKPOINTS = {
    'session_batch_test.go': 'A4', 'session_completion_test.go': 'A4', 'session_textedit_test.go': 'A4',
    'session_apistate_test.go': 'A3', 'session_createprogram_test.go': 'A3', 'session_temporary_test.go': 'A3',
    'decoder_test.go': 'A5: the Phase 0 corpus encoding parity covers decoding of every test input; the named cases need their equivalent-coverage note or a port',
    'encoder_test.go': 'A5: the two api baselines through a Rust encoder comparison',
}


def go_tests():
    rows = []
    for path in sorted((ROOT / 'upstream/tsc/internal/api').rglob('*_test.go')):
        package = 'api' if path.parent.name == 'api' else f'api/{path.parent.name}'
        text = path.read_text()
        for match in TEST.finditer(text):
            name = match.group(1)
            if name == 'TestMain':
                continue
            route = ROUTES.get((package, name)) or f"WORK ({CHECKPOINTS.get(path.name, 'A5')})"
            line = text.count('\n', 0, match.start()) + 1
            rows.append((package, name, f'{path.relative_to(ROOT)}:{line}', route))
    return rows


def client_cases(results):
    cases = Counter()
    skips = Counter()
    for line in Path(results).read_text().splitlines():
        row = json.loads(line)
        if row['id'] == row.get('parent'):
            continue
        name = row['parent'].split('/', 1)[1]
        cases[name] += 1
        if row['state'] == 'skip':
            skips[name] += 1
    return cases, skips


def markdown(results):
    cases, skips = client_cases(results)
    tests = go_tests()
    work = sum(1 for row in tests if row[3].startswith('WORK'))
    lines = ['# Phase 6 pinned test routing', '',
             'Generated by `python3 tools/phase6/jsapi/inventory.py --results RESULTS --markdown docs/PHASE6-tests.md`',
             'from a native run of the `jsapi` suite and the pinned `internal/api` Go tests. It records',
             'routes, not results: suite rows need the actual native and Rust outcomes before they count,',
             'and a Rust test named here ports the observation it names, not every neighbouring case.', '',
             '## The pinned client suites (`jsapi`)', '',
             'One variant per test file, one row per case; the native run of the same command fixes the',
             'denominator and the native skip set.', '',
             '| File | Cases | Native skips |', '| --- | ---: | ---: |']
    lines.extend(f'| `{name}` | {count} | {skips[name]} |' for name, count in sorted(cases.items()))
    lines += [f'| total | {sum(cases.values())} | {sum(skips.values())} |', '',
              '## Direct Go tests of `internal/api`', '',
              f'{len(tests)} tests; **{work}** still routed to work. `WORK (A<n>)` names the checkpoint that',
              'owes the port or its equivalent-coverage explanation.', '',
              '| Pinned test | Source | Route |', '| --- | --- | --- |']
    lines.extend(f'| `{package}/{name}` | `{source}` | {route} |' for package, name, source, route in tests)
    lines += ['', '## Baselines', '',
              '`testdata/baselines/reference/api/encodeSourceFile.txt` and `encodeSourceFileWithUnicodeEscapes.txt`',
              'are the encoder goldens of `encoder_test.go`; A5 compares them through a Rust encoder test.', '']
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--results', required=True, help='results.ndjson of a jsapi run')
    parser.add_argument('--markdown', type=Path, required=True)
    args = parser.parse_args()
    args.markdown.write_text(markdown(args.results))


if __name__ == '__main__':
    main()
