#!/usr/bin/env python3
"""Source routing audit; compiled Go lists, when supplied, validate the roster."""
from __future__ import annotations
import argparse
from collections import Counter
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[3]
TEST = re.compile(r'^func (Test\w+)\(\w+ \*testing\.T\)\s*\{', re.M)


def collect(root: Path = ROOT) -> list[dict]:
    references: dict[str, list[str]] = {}
    for path in sorted((root / 'crates').rglob('*.rs')):
        text = path.read_text()
        # A name in a source comment is evidence of an observation port, not
        # certification that every native subcase is implemented or passing.
        for number, line in enumerate(text.splitlines(), 1):
            if '//' not in line:
                continue
            for name in re.findall(r'\bTest[A-Z]\w*', line.split('//', 1)[1]):
                references.setdefault(name, []).append(f'{path.relative_to(root)}:{number}')
    rows = []
    internal = root / 'upstream/tsc/internal'
    for area in ('project', 'lsp', 'ls', 'fourslash/tests'):
        for path in sorted((internal / area).rglob('*_test.go')):
            text = path.read_text()
            matches = list(TEST.finditer(text))
            for i, match in enumerate(matches):
                name = match.group(1)
                body = text[match.end():matches[i + 1].start() if i + 1 < len(matches) else len(text)]
                package = str(path.parent.relative_to(internal))
                source = f'{path.relative_to(root)}:{text.count(chr(10), 0, match.start()) + 1}'
                if area == 'fourslash/tests':
                    route = f'fourslash/{name}'
                elif package == 'lsp' and (
                    'lsptestutil.NewLSPClient(' in body or path.name in {
                        'server_completion_test.go', 'server_contentmapper_test.go',
                        'server_progress_test.go', 'server_projectinfo_test.go',
                        'server_projectreference_updates_test.go', 'server_semantictokens_test.go'}):
                    route = f'lsp/{name}' if name != 'TestReplay' else 'fixture-dependent replay; no default corpus route'
                elif package == 'project/ata':
                    route = {
                        'TestValidatePackageName': 'Rust observation port: tsr_project::ata::tests::pinned_package_name_validation',
                        'TestInstallNpmPackages': 'Rust mock-executor port: tsr_project::ata::tests::pinned_npm_long_command_runs_both_batches_even_after_failure; real npm integration is opt-in',
                        'TestDiscoverTypings': 'Rust observation family: crates/tsr_project/src/ata/tests.rs (pinned_discovery_* and manifest/cache cases); native skipped local @types deduplication remains excluded',
                        'TestATA': 'Rust observation family: crates/tsr_project/src/session/ata/tests.rs (pinned_* acquisition cases); no claim of all native subcases',
                    }[name]
                elif name in references:
                    route = 'Rust source references: ' + ', '.join(sorted(set(references[name])))
                else:
                    route = 'WORK: exact native-test-to-Rust-test assignment unverified'
                rows.append(dict(package=package, name=name, source=source, route=route,
                                 skip_call='t.Skip(' in body or 't.Skipf(' in body,
                                 first_statement_skip=bool(re.match(r'\s*t\.Skip\(', body)),
                                 state_baseline='@stateBaseline: true' in body,
                                 mapper=path.name.startswith('contentMapper'),
                                 tsc_prebuild='@tsc:' in body))
    return rows


def verify_lists(rows: list[dict], specs: list[str]) -> None:
    for spec in specs:
        package, filename = spec.split('=', 1)
        if package not in {row['package'] for row in rows}:
            raise ValueError(f'unknown package: {package}')
        actual = {line.strip() for line in Path(filename).read_text().splitlines()
                  if re.fullmatch(r'Test\w+', line.strip()) and line.strip() != 'TestMain'}
        expected = {row['name'] for row in rows if row['package'] == package}
        if actual != expected:
            raise ValueError(f'{package}: source-only={sorted(expected - actual)}, compiled-only={sorted(actual - expected)}')


def markdown(rows: list[dict], verified: list[str]) -> str:
    counts = Counter(row['package'] for row in rows)
    fs = [row for row in rows if row['package'] == 'fourslash/tests']
    lines = ['# Phase 5 pinned test routing inventory', '',
             'Generated by `python3 tools/phase5/harness/inventory.py --markdown docs/PHASE5-tests.md`.', '',
             'This is a source audit of the pinned Go top-level test functions, excluding `TestMain`.',
             'It records routes and source references, not execution results. Suite routes require the',
             'compiled harness list and actual Go/Rust results before they confer acceptance credit.',
             'Rust comment references identify ported observations; they do not certify all subcases.',
             'The CLI JSON output contains every fourslash id; the table below groups that family.',
             'WORK rows require an exact port assignment or implementation, even where family coverage',
             'exists in the development checks. Runtime skip events determine the executable denominator.', '',
             'Validate a compiled roster with `--compiled-list PACKAGE=FILE`, repeated per package.',
             'FILE is the captured output of that package test binary with `-test.list ^Test`.',
             'Build tags, platform constraints and generated tests can change runtime membership.',
             'For host-filtered binaries use `runner.py list SUITE --prepared DIR`: its preparation',
             'records `go list -json` TestGoFiles/XTestGoFiles and GOOS/GOARCH, then validates',
             'the compiled list against exactly those included sources. The inventory CLI',
             '`--compiled-list` check compares the whole source roster and detects omissions.',
             '',
             'The native-host compiled fourslash list observed during L7 bring-up contains',
             '**4,534 tests**, excluding 13 functions in `*_js_test.go` files. Go interprets',
             'that filename suffix as GOOS=js. These are platform exclusions, not runtime skips;',
             'the 4,547-function source roster remains visible in the CLI JSON inventory.',
             'The acceptance denominator N is not measured by this list; it requires Go outcomes.', '',
             'Compiled rosters checked in this generation: ' + (', '.join(verified) if verified else '**none**') + '.', '',
             '| Package | Source test functions |', '| --- | ---: |']
    lines.extend(f'| `{package}` | {count} |' for package, count in sorted(counts.items()))
    lines += ['', f'Fourslash source facts: {len(fs)} functions; '
              f'{sum(r["first_statement_skip"] for r in fs)} first-statement skip calls; '
              f'{sum(r["state_baseline"] for r in fs)} state-baseline functions; '
              f'{sum(r["mapper"] for r in fs)} contentMapper-file functions; '
              f'{sum(r["tsc_prebuild"] for r in fs)} prebuild functions.', '',
              'A skip call in the source region up to the next test declaration is flagged below;',
              'helpers in that region may contain it. This is not an observed skip.',
              'Compiler-option-driven skips reside in shared harness code and are not inferred here.', '',
              'Development routes: `tools/phase5/project/check.py` compares original Go snapshot-writer',
              'bytes; `tools/phase5/lsp/check.py` carries selected native client tests; the other scripts',
              'under `tools/phase5/lsp/` compare bounded synthetic scenarios. Their documented past',
              'results are not rerun results of this inventory or full pinned corpus acceptance.', '',
              'L6 already added the project content-mapper observation ports referenced below, ATA',
              'discovery/validation/mock-install/session coverage, and the carried',
              '`TestSetContentMapperContributionsBeforeDidOpen` client check. Exact residuals',
              'remain runtime evidence work. The L7 planning reference predates those ports.',
              'Its custom API-session',
              'wire claim also conflicts with the L6 record, which assigns that handshake to Phase 6.', '',
              '| Pinned test | Source | Route / evidence | Skip call in source region |',
              '| --- | --- | --- | --- |']
    lines.append('| `fourslash/tests/Test*` (4,547 functions) | `upstream/tsc/internal/fourslash/tests/*_test.go` | `fourslash/<TestName>`; enumerate all ids with the CLI JSON output | runtime authority |')
    lines.extend(f'| `{r["package"]}/{r["name"]}` | `{r["source"]}` | {r["route"]} | {"yes" if r["skip_call"] else ""} |' for r in rows if r['package'] != 'fourslash/tests')
    return '\n'.join(lines) + '\n'


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--markdown', type=Path)
    parser.add_argument('--compiled-list', action='append', default=[])
    args = parser.parse_args()
    rows = collect()
    verify_lists(rows, args.compiled_list)
    if args.markdown:
        args.markdown.write_text(markdown(rows, [s.split('=', 1)[0] for s in args.compiled_list]))
    else:
        print(json.dumps(rows, indent=2))


if __name__ == '__main__':
    main()
